# Generated by Django 3.2.12 on 2024-07-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(default='N/A', max_length=50)),
                ('released_date', models.DateField(blank=True, null=True)),
                ('rated', models.CharField(default='Not Rated', max_length=20)),
                ('imdb_rating', models.TextField(blank=True, null=True)),
                ('genres', models.CharField(max_length=255)),
                ('plot', models.TextField(default='No plot available')),
                ('director', models.CharField(max_length=255)),
                ('writer', models.CharField(default='No Data Available', max_length=255)),
                ('awards', models.TextField(default='No awards available')),
                ('language', models.CharField(default='N/A', max_length=100)),
                ('poster_url', models.CharField(max_length=455)),
                ('website', models.URLField(blank=True, max_length=455, null=True)),
                ('imdb_id', models.CharField(max_length=20)),
                ('imdb_votes', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(default='Unknown', max_length=50)),
                ('country', models.CharField(default='Unknown', max_length=100)),
                ('actors', models.TextField(default='Unknown')),
                ('boxoffice', models.CharField(default='Unknown', max_length=100, null=True)),
                ('rotten_tomatoes_rating', models.CharField(blank=True, default='N/A', max_length=20, null=True)),
                ('runtime', models.CharField(blank=True, default='N/A', max_length=20, null=True)),
                ('active', models.BooleanField(default=False)),
                ('trailer_url', models.CharField(blank=True, max_length=455, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=455, null=True)),
                ('backdrop_url', models.CharField(blank=True, max_length=455, null=True)),
                ('status', models.CharField(default='Unknown', max_length=100)),
                ('original_language', models.CharField(default='Unknown', max_length=100)),
                ('homepage', models.URLField(blank=True, max_length=455, null=True)),
            ],
        ),
    ]
