# Generated by Django 3.2.12 on 2024-04-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('released_date', models.DateField(blank=True, null=True)),
                ('rated', models.CharField(max_length=20)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('genres', models.CharField(max_length=255)),
                ('plot', models.TextField(default='No plot available')),
                ('director', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=100)),
                ('poster_url', models.URLField(max_length=455)),
                ('imdb_id', models.CharField(max_length=20)),
                ('imdb_votes', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('actors', models.TextField()),
                ('boxoffice', models.CharField(max_length=100)),
                ('rotten_tomatoes_rating', models.CharField(blank=True, max_length=20, null=True)),
                ('runtime', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
