# Generated by Django 3.2.12 on 2024-05-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_handling_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='boxoffice',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rated',
            field=models.CharField(default='Not Rated', max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rotten_tomatoes_rating',
            field=models.CharField(blank=True, default='N/A', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.CharField(blank=True, default='N/A', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
