# Generated by Django 3.2.12 on 2024-07-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_handling_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCompanies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo_path', models.CharField(max_length=455)),
                ('origin_country', models.CharField(max_length=100)),
            ],
        ),
    ]
