# Generated by Django 3.2.12 on 2024-07-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_handling_app', '0002_productioncompanies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='production_companies',
            field=models.ManyToManyField(to='database_handling_app.ProductionCompanies'),
        ),
    ]
