# Generated by Django 3.2.12 on 2024-06-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_handling_app', '0002_auto_20240514_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.TextField(blank=True, null=True),
        ),
    ]
