# Generated by Django 3.2.12 on 2024-06-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_handling_app', '0003_auto_20240601_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, max_length=455, null=True),
        ),
    ]
