# Generated by Django 3.2.12 on 2024-07-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_handling_app', '0003_movie_production_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCountries',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('iso_3166_1', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SpokenLanguages',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('english_name', models.CharField(max_length=255)),
                ('iso_639_1', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='production_countries',
            field=models.ManyToManyField(to='database_handling_app.ProductionCountries'),
        ),
        migrations.AddField(
            model_name='movie',
            name='spoken_languages',
            field=models.ManyToManyField(to='database_handling_app.SpokenLanguages'),
        ),
    ]
