# Generated by Django 3.2.12 on 2024-07-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_handling_app', '0004_auto_20240715_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='productioncompanies',
            name='imdb_id',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='productioncountries',
            name='imdb_id',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='spokenlanguages',
            name='imdb_id',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
