# Generated by Django 3.2.12 on 2024-06-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_handling_app', '0004_movie_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='awards',
            field=models.TextField(default='No awards available'),
        ),
        migrations.AddField(
            model_name='movie',
            name='website',
            field=models.URLField(blank=True, max_length=455, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='writer',
            field=models.CharField(default='No Data Available', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
