# Generated by Django 3.2.12 on 2024-07-15 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_handling_app', '0005_auto_20240716_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='production_companies',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='production_countries',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='spoken_languages',
        ),
    ]
