# Generated by Django 3.2.12 on 2024-07-16 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_handling_app', '0006_auto_20240716_0127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductionCompanies',
        ),
        migrations.DeleteModel(
            name='ProductionCountries',
        ),
        migrations.DeleteModel(
            name='SpokenLanguages',
        ),
    ]
