# Generated by Django 3.2.12 on 2024-07-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_handling_app', '0008_movie_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='homepage',
            field=models.URLField(blank=True, max_length=455, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='origin_country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='original_language',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='production_companies',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='movie',
            name='production_countries',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='movie',
            name='spoken_languages',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='logo_url',
            field=models.TextField(blank=True, max_length=455, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.TextField(blank=True, max_length=455, null=True),
        ),
    ]
