# Generated by Django 3.2.12 on 2024-07-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_handling_app', '0008_auto_20240717_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backdrops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect_ratio', models.FloatField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('iso_639_1', models.CharField(max_length=10)),
                ('file_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('known_for_department', models.CharField(max_length=255)),
                ('character', models.CharField(max_length=255)),
                ('profile_path', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('known_for_department', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('profile_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect_ratio', models.FloatField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('iso_639_1', models.CharField(max_length=10)),
                ('file_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OriginCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Posters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect_ratio', models.FloatField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('iso_639_1', models.CharField(max_length=10)),
                ('file_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_639_1', models.CharField(max_length=10)),
                ('iso_3166_1', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('official', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='Backdrops',
            field=models.ManyToManyField(to='database_handling_app.Backdrops'),
        ),
        migrations.AddField(
            model_name='movie',
            name='Logos',
            field=models.ManyToManyField(to='database_handling_app.Logos'),
        ),
        migrations.AddField(
            model_name='movie',
            name='Posters',
            field=models.ManyToManyField(to='database_handling_app.Posters'),
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(to='database_handling_app.Cast'),
        ),
        migrations.AddField(
            model_name='movie',
            name='crew',
            field=models.ManyToManyField(to='database_handling_app.Crew'),
        ),
        migrations.AddField(
            model_name='movie',
            name='origin_countries',
            field=models.ManyToManyField(to='database_handling_app.OriginCountry'),
        ),
        migrations.AddField(
            model_name='movie',
            name='videos',
            field=models.ManyToManyField(to='database_handling_app.Video'),
        ),
    ]
