# Generated by Django 3.2.12 on 2024-07-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_handling_app', '0009_auto_20240719_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
