# Generated by Django 3.2.12 on 2024-07-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_handling_app', '0010_auto_20240711_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.CharField(max_length=455),
        ),
    ]
