# Generated by Django 3.2.12 on 2024-07-19 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_handling_app', '0010_video_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='country',
        ),
    ]
