# Generated by Django 3.2.12 on 2024-07-19 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_handling_app', '0011_auto_20240720_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='website',
        ),
    ]
