# Generated by Django 3.2.12 on 2024-07-20 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_handling_app', '0012_remove_movie_website'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='backdrops',
            table='database_handling_app_backdrops',
        ),
        migrations.AlterModelTable(
            name='logos',
            table='database_handling_app_logos',
        ),
        migrations.AlterModelTable(
            name='posters',
            table='database_handling_app_posters',
        ),
        migrations.AlterModelTable(
            name='video',
            table='database_handling_app_video',
        ),
    ]
