# Generated by Django 3.2.12 on 2024-07-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_handling_app', '0012_productioncompany_remove_movie_production_countries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='origin_country',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='production_companies',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='spoken_languages',
        ),
    ]
