# Generated by Django 3.2.12 on 2024-07-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_handling_app', '0013_auto_20240721_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='Backdrops',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Logos',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Posters',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backdrops', models.ManyToManyField(to='database_handling_app.Backdrops')),
                ('logos', models.ManyToManyField(to='database_handling_app.Logos')),
                ('posters', models.ManyToManyField(to='database_handling_app.Posters')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='images',
            field=models.ManyToManyField(to='database_handling_app.Images'),
        ),
    ]
