# Generated by Django 3.2.12 on 2024-07-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_handling_app', '0013_auto_20240715_1929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductionCompany',
        ),
        migrations.AlterField(
            model_name='movie',
            name='boxoffice',
            field=models.CharField(default='Unknown', max_length=100, null=True),
        ),
    ]
