# Generated by Django 3.2.12 on 2024-07-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_handling_app', '0014_auto_20240722_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='images',
        ),
        migrations.AddField(
            model_name='movie',
            name='Backdrops',
            field=models.ManyToManyField(to='database_handling_app.Backdrops'),
        ),
        migrations.AddField(
            model_name='movie',
            name='Logos',
            field=models.ManyToManyField(to='database_handling_app.Logos'),
        ),
        migrations.AddField(
            model_name='movie',
            name='Posters',
            field=models.ManyToManyField(to='database_handling_app.Posters'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
