# Generated by Django 3.2.12 on 2024-07-22 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_handling_app', '0015_auto_20240722_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='Backdrops',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Logos',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Posters',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backdrops', models.ManyToManyField(to='database_handling_app.Backdrops')),
                ('logos', models.ManyToManyField(to='database_handling_app.Logos')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='database_handling_app.movie')),
                ('posters', models.ManyToManyField(to='database_handling_app.Posters')),
            ],
        ),
    ]
