# Generated by Django 3.2.12 on 2024-07-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_handling_app', '0018_alter_logos_iso_639_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backdrops',
            name='iso_639_1',
            field=models.CharField(blank=True, default='en', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='posters',
            name='iso_639_1',
            field=models.CharField(blank=True, default='en', max_length=10, null=True),
        ),
    ]
